"use client";

import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import type { DailyTask } from "@/lib/daily-tasks/actions";

interface TaskDetailSheetProps {
  task: DailyTask | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const EXECUTOR_LABELS: Record<string, string> = {
  self: "Self / Teammate",
  n8n: "n8n Automation",
  claude_api: "Claude API",
  freelancer: "Freelancer",
};

export function TaskDetailSheet({
  task,
  open,
  onOpenChange,
}: TaskDetailSheetProps) {
  if (!task) return null;

  const assignee =
    task.assigned_profile?.display_name ||
    task.assigned_profile?.email ||
    "Unassigned";

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent>
        <SheetHeader>
          <SheetTitle className="text-left">{task.title}</SheetTitle>
        </SheetHeader>

        <div className="mt-4 space-y-4">
          <div className="flex flex-wrap gap-2">
            <Badge variant="outline">{task.priority}</Badge>
            <Badge variant="outline">{task.task_type}</Badge>
            <Badge variant="outline">{task.status.replace("_", " ")}</Badge>
          </div>

          {task.description && (
            <div>
              <p className="text-xs font-medium text-gray-500 mb-1">
                Description
              </p>
              <p className="text-sm whitespace-pre-wrap">{task.description}</p>
            </div>
          )}

          <Separator />

          <div className="grid grid-cols-2 gap-3 text-sm">
            <div>
              <p className="text-xs font-medium text-gray-500">Executor</p>
              <p>{EXECUTOR_LABELS[task.executor_type] || task.executor_type}</p>
            </div>
            <div>
              <p className="text-xs font-medium text-gray-500">Assigned to</p>
              <p>{assignee}</p>
            </div>
            <div>
              <p className="text-xs font-medium text-gray-500">Scheduled</p>
              <p>{task.scheduled_date}</p>
            </div>
            <div>
              <p className="text-xs font-medium text-gray-500">Generated by</p>
              <p className="capitalize">{task.generated_by}</p>
            </div>
          </div>

          {task.completed_at && (
            <>
              <Separator />
              <div>
                <p className="text-xs font-medium text-gray-500 mb-1">
                  Completed at
                </p>
                <p className="text-sm">
                  {new Date(task.completed_at).toLocaleString()}
                </p>
              </div>
            </>
          )}

          {task.outcome_notes && (
            <div>
              <p className="text-xs font-medium text-gray-500 mb-1">
                Outcome Notes
              </p>
              <p className="text-sm whitespace-pre-wrap">
                {task.outcome_notes}
              </p>
            </div>
          )}

          {task.source_strategy && (
            <div>
              <p className="text-xs font-medium text-gray-500 mb-1">
                Source Strategy
              </p>
              <p className="text-sm">{task.source_strategy}</p>
            </div>
          )}
        </div>
      </SheetContent>
    </Sheet>
  );
}
